services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: urundb
      POSTGRES_USER: urunuser
      POSTGRES_PASSWORD: guclu-bir-sifre
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./website
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urundb
      SPRING_DATASOURCE_USERNAME: urunuser
      SPRING_DATASOURCE_PASSWORD: guclu-bir-sifre

  frontend:
    build: ./urun-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: