spring.application.name=website
spring.datasource.url=jdbc:postgresql://localhost:5432/urundb
spring.datasource.username=urunuser
spring.datasource.password=guclu-bir-sifre
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
